---
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ${CONFIG}/heimdall:/config
    ports:
      - 8083:80  # Changed from 80:80 to avoid conflict
    restart: unless-stopped
    # networks:
    #   - traefik-public
    labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.heimdall.rule=Host(`heimdall.local`)"
      # - "traefik.http.services.heimdall.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.monitor-only=true"

# networks:
#   traefik-public:
#     external: true
