---
services:
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "9001:9000/tcp"  # Changed to avoid conflict
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer_data:/data
    restart: always
    # networks:
    #   - traefik-public
    labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.portainer.rule=Host(`portainer.local`)"
      # - "traefik.http.services.portainer.loadbalancer.server.port=9000"

# networks:
#   traefik-public:
#     external: true